[package]
name = "rustris"
version = "0.2.1"
edition = "2021"
build = "build.rs"

[dependencies]
find_folder = "0.3.0"
macroquad = { version = "0.3.25", features = ["log"] }
strum = { version = "0.24", features = ["derive"] }
rand = "0.8"
rand_xoshiro = "0.6"
log = "0.4"
simplelog = "0.12.0"
time = "0.3.17"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
